### ISSUE TITLE
stuck on kindlefusion startup

### ISSUE THREAD

**Issue by mdavatol** [diggedypomme/Kindlefusion#3]
Its very likely I did something wrong because I have 'starting KF 17' on the screen for a long time and it hasn't moved.

**Comment by diggedypomme** [comment]
Hi, sorry to hear that. I think the most likely cause is that the libraries are not installed. 

If you can SSH to it, go to the /mnt/us/kindlefusion folder and run the [stable17.py] (https://github.com/diggedypomme/Kindlefusion/blob/main/add_to_kindle/kindlefusion/stable17.py)
directly with
python3 stable17.py
Then you can see the error messages that might come from python.

If it is the libraries, you should be able to run this from kual or ssh (the install libraries option on kual)
https://github.com/diggedypomme/Kindlefusion/blob/main/add_to_kindle/extensions/kindlefusion/bin/libraries.sh

Kind regards
